#!/bin/sh
DB2PATH=/home/db2inst2/sqllib
CC=gcc
CFLAGS="-Wno-narrowing -I$DB2PATH/include"
LIBS="-L$DB2PATH/lib -ldb2"

db2 connect to cs348
db2 prep bibauthor.sqc bindfile
db2 bind bibauthor.bnd
db2 connect reset
$CC $CFLAGS -o bibauthor bibauthor.c util.c $LIBS

# db2 connect to cs348
# db2 prep bibcontent.sqc bindfile
# db2 bind bibcontent.bnd
# db2 connect reset
# $CC $CFLAGS -o bibcontent bibcontent.c util.c $LIBS
